"""Static default configuration values for Mira Portfolio."""

APP_NAME = "Mira Portfolio"
COMPANY_NAME = "Mira"
VERSION = "0.1.0"
THEME = "dark"
LANGUAGE = "en"
DEFAULT_CURRENCY = "TRY"
AUTO_BACKUP = True
AUTO_SNAPSHOT = True
UPDATE_INTERVAL = 60
ENVIRONMENT = "development"
DEBUG = False
LOG_LEVEL = "INFO"
DATABASE_DIRECTORY_NAME = "database"
EXPORT_DIRECTORY_NAME = "exports"
BACKUP_DIRECTORY_NAME = "backups"
DATABASE_FILENAME = "portfolio.db"
LOG_FILENAME = "mira-portfolio.log"
LOG_ROTATION_BYTES = 5 * 1024 * 1024
LOG_RETENTION_DAYS = 14

PREFERENCES_DIRECTORY_NAME = "settings"
PREFERENCES_FILENAME = "preferences.json"
PREFERENCES_FORMAT_VERSION = 1
PREFERENCES_MAX_FILE_BYTES = 16 * 1024

SUPPORT_DIRECTORY_NAME = "support"
SUPPORT_BUNDLE_EXTENSION = ".mirasupport"
SUPPORT_BUNDLE_FORMAT_VERSION = 1
SUPPORT_BUNDLE_MAX_MEMBER_COUNT = 10
SUPPORT_BUNDLE_MAX_JSON_BYTES = 256 * 1024
SUPPORT_BUNDLE_MAX_LOG_COUNT = 5
SUPPORT_BUNDLE_MAX_LOG_BYTES = 2 * 1024 * 1024
SUPPORT_BUNDLE_MAX_TOTAL_LOG_BYTES = 8 * 1024 * 1024
SUPPORT_BUNDLE_MAX_UNCOMPRESSED_BYTES = 10 * 1024 * 1024
SUPPORT_BUNDLE_MAX_ARCHIVE_BYTES = 16 * 1024 * 1024
SUPPORT_BUNDLE_MAX_BACKUP_SCAN_COUNT = 100
